/*
 * ESP32 Relay Controller for Arduino IoT Cloud
 * 
 * Controls a relay via two cloud variables (powerPulse and resetPulse).
 * Optimized for low power consumption.
 * 
 * Hardware:
 * - Relay connected to pin 26 (active LOW).
 * - ESP32 board.
 * 
 * Configuration:
 * - All sensitive data in arduino_secrets.h.
 * - Adjustable timings and pin assignments below.
 * 
 * Repository: https://github.com/SolarisPKN/SolarisPKN-Control
 */

#include "arduino_secrets.h"
#include "thingProperties.h"   // Generated by Arduino IoT Cloud

#include <esp_bt.h>
#include <esp_wifi.h>
#include <esp_pm.h>

// ============================================================
//  CONFIGURATION CONSTANTS (change as needed)
// ============================================================

// Pin definitions
#define RELAY_PIN           26
#define RELAY_ACTIVE_LOW    true   // true: LOW activates relay, HIGH deactivates

// Timing (milliseconds)
#define PULSE_TIME_MS       500
#define FORCED_PULSE_TIME_MS 15000

// Serial communication
#define SERIAL_BAUD_RATE    115200

// Power management
#define CPU_FREQ_MHZ        80      // 80 MHz (good balance)
#define MIN_CPU_FREQ_MHZ    10      // For light sleep
#define WIFI_PS_MODE        WIFI_PS_MAX_MODEM   // MAX_MODEM or MIN_MODEM

// ============================================================
//  GLOBAL STATE
// ============================================================

static bool   s_relayActive = false;
static uint32_t s_relayStartTime = 0;
static uint32_t s_relayDuration = 0;

// ============================================================
//  SETUP
// ============================================================

void setup() {
  // Serial
  Serial.begin(SERIAL_BAUD_RATE);
  delay(100);

  Serial.println("\n===== ESP32 RELAY CONTROLLER =====");
  Serial.println("[INIT] Starting setup...");

  // ---- GPIO ----
  pinMode(RELAY_PIN, OUTPUT);
  // Set initial state (inactive)
  digitalWrite(RELAY_PIN, RELAY_ACTIVE_LOW ? HIGH : LOW);
  Serial.println("[GPIO] Relay pin configured.");

  // ---- Power optimizations ----
  applyPowerOptimizations();

  // ---- Connect to Arduino IoT Cloud ----
  initProperties();
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::CONNECT, onCloudConnect);
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::DISCONNECT, onCloudDisconnect);
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  Serial.println("[INIT] Setup complete.\n");
}

// ============================================================
//  POWER OPTIMIZATIONS
// ============================================================

void applyPowerOptimizations() {
  Serial.println("[PWR] Applying optimizations...");

  // 1. Set CPU frequency
  setCpuFrequencyMhz(CPU_FREQ_MHZ);
  Serial.printf("  CPU: %d MHz\n", getCpuFrequencyMhz());

  // 2. Disable Bluetooth (not used)
  esp_bt_controller_disable();
  Serial.println("  Bluetooth: OFF");

  // 3. WiFi power save mode
  esp_wifi_set_ps(WIFI_PS_MODE);
  #if WIFI_PS_MODE == WIFI_PS_MAX_MODEM
    Serial.println("  WiFi: MAX_PS (max saving)");
  #else
    Serial.println("  WiFi: MIN_PS (min saving)");
  #endif

  // 4. Light sleep automatic
  esp_pm_config_esp32_t pm_config = {
    .max_freq_mhz = CPU_FREQ_MHZ,
    .min_freq_mhz = MIN_CPU_FREQ_MHZ,
    .light_sleep_enable = true
  };
  esp_pm_configure(&pm_config);
  Serial.println("  Light Sleep: ON");
}

// ============================================================
//  CLOUD EVENT CALLBACKS
// ============================================================

void onCloudConnect() {
  Serial.println("[CLOUD] ✅ Connected.");
  Serial.print("[NET] IP: ");
  Serial.println(WiFi.localIP());
}

void onCloudDisconnect() {
  Serial.println("[CLOUD] ❌ Disconnected.");
}

// ============================================================
//  CLOUD VARIABLE CALLBACKS
// ============================================================

void onPowerPulseChange() {
  if (powerPulse) {
    Serial.println("[CMD] ⚡ Normal pulse received.");
    activateRelay(PULSE_TIME_MS);
    powerPulse = false;   // Reset cloud variable
  }
}

void onResetPulseChange() {
  if (resetPulse) {
    Serial.println("[CMD] 🔄 Forced pulse (15s) received.");
    activateRelay(FORCED_PULSE_TIME_MS);
    resetPulse = false;
  }
}

// ============================================================
//  RELAY CONTROL (non-blocking)
// ============================================================

void activateRelay(uint32_t durationMs) {
  if (s_relayActive) {
    Serial.println("[RELAY] ⚠️  Already active, ignoring.");
    return;
  }

  s_relayActive = true;
  s_relayStartTime = millis();
  s_relayDuration = durationMs;
  digitalWrite(RELAY_PIN, RELAY_ACTIVE_LOW ? LOW : HIGH);
  Serial.printf("[RELAY] Activated for %lu ms.\n", durationMs);
}

void updateRelay() {
  if (!s_relayActive) return;

  if (millis() - s_relayStartTime >= s_relayDuration) {
    digitalWrite(RELAY_PIN, RELAY_ACTIVE_LOW ? HIGH : LOW);
    s_relayActive = false;
    Serial.println("[RELAY] Deactivated.");
  }
}

// ============================================================
//  MAIN LOOP
// ============================================================

void loop() {
  // Cloud services
  ArduinoCloud.update();

  // Relay state machine
  updateRelay();

  // Small delay to allow light sleep
  delay(5);
}