// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char DEVICE_LOGIN_NAME[] = "ID DEL ESP32";

const char SSID[] = SECRET_SSID;
const char PASS[] = SECRET_OPTIONAL_PASS;
const char DEVICE_KEY[] = SECRET_DEVICE_KEY;

void onPowerPulseChange();
void onResetPulseChange();

bool powerPulse;
bool resetPulse;
bool pcEncendida;

void initProperties() {
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(powerPulse, READWRITE, ON_CHANGE, onPowerPulseChange);
  ArduinoCloud.addProperty(resetPulse, READWRITE, ON_CHANGE, onResetPulseChange);
  ArduinoCloud.addProperty(pcEncendida, READ, ON_CHANGE, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);